### PR TITLE
add MarsProtocol to stakingservice page

### PR DESCRIPTION
**Pull request by Jodragon**
Adding MarsProtocol to the Beacon Chain Explorer [Staking Services Page](https://beaconcha.in/stakingServices).
Name Of Service- MarsProtocol
Website- www.marsprotocol.com

Our users are institutions, so the registration needs to be reviewed, and the fee is also charged in the form of a bill, so if you want to register, please give me your account number?

### CODE REVIEW

**Comment by Jodragon** [comment]
@Buttaa Hello, what is the reason for the rejection? How should I apply correctly?

**Comment by Buttaa** [comment]
Hey there! I noticed that the website and product don't seem very reliable, and there are some missing SSL credentials. We don't have a formal application process, but we have the right to decline projects that we feel don't meet our standards.

**Comment by Jodragon** [comment]
@Buttaa It seems that the certificate has expired. Can we resubmit after the fix, or open this again?

**Comment by Jodragon** [comment]
@Buttaa https://www.marsprotocol.com/ Please take a look again, https is fine

**Pull request closed without merging**
