### PR TITLE
(NOBIDS) Update stakingServices.html

### PR DESCRIPTION
**Pull request by andreilicious23**
Launchnodes' price per validator node is $240 per year for Teku, which makes it $20 per month. Thank you.

### <samp>🤖 Generated by Copilot at 18c3744</samp>

Updated the fee for LaunchNodes in the staking services comparison table on the website. This reflects the current pricing of the staking service provider.

### CODE REVIEW

**Comment by Buttaa** [comment]
> Launchnodes' price per validator node is $240 per year for Teku, which makes it $20 per month. Thank you.
> 
> ### 🤖 Generated by Copilot at [18c3744](https://github.com/gobitfly/eth2-beaconchain-explorer/commit/18c37442ed6f368c63e5cf0314f049104b57afcc)
> Updated the fee for LaunchNodes in the staking services comparison table on the website. This reflects the current pricing of the staking service provider.

@andreilicious23 , your website https://www.launchnodes.com/ethereum-solo-staking/ shows "$594 per node", which ends up being $49.5/m. 
Also ptal at the supermajority client column.

**Comment by andreilicious23** [comment]
Hey. We offer two clients. Prysmatic is 594usd and Teku is 240usd, hence
the change.

These prices are outlined here:
https://www.launchnodes.com/ln_products/ethereum-validator-node-prysmatic-client/

Thank you for your help.

Andrei

**Comment by Buttaa** [comment]
Thanks @andreilicious23 , 

I am still missing the information for Super Majority client - 

`<td data-column="No Supermajority client" style="text-align: center;">❓</td>`

**Comment by Buttaa** [comment]
> 

Hi @andreilicious23 you can either edit your current PR to include the client information or create a new PR. It's totally up to you!

**Comment by andreilicious23** [comment]
Hi @Buttaa. Supermajority data is updated as well now. Thanks.

**Comment by Buttaa** [comment]
> Hi @Buttaa. Supermajority data is updated as well now. Thanks.

Thanks @andreilicious23 , based on your last comment "We use geth as supermajority. ", please use the ❌ icon for the column

**Review by recy21 — APPROVED** [review]

**Pull request merged**
