### PR TITLE
Add skypool to staking service

### PR DESCRIPTION
**Pull request by Azard**

### CODE REVIEW

**Comment by Azard** [comment]
@guybrush @Buttaa need a review 👍

**Comment by Buttaa** [comment]
@Azard  please add an english version of the website. I am struggling to understand what you guys are offering.

**Comment by Azard** [comment]
> @Azard please add an english version of the website. I am struggling to understand what you guys are offering.

image

It can change language, we will add a international icon on language switch today

**Comment by Azard** [comment]
> @Azard please add an english version of the website. I am struggling to understand what you guys are offering.

image

Thanks for advice, we have add a icon for i18n and language default using English

**Comment by Azard** [comment]
@guybrush @qu0b @Buttaa 
hi, could you take a review and merge this PR?

**Review by Buttaa — APPROVED** [review]

**Pull request merged**
