### PR TITLE
Add Prysm v3 support

### LINKED ISSUE #1165: unknown method ListBlocksAltair for service ethereum.eth.v1alpha1.BeaconChain
ListBlocksAltair did not find method ListBlocksAltair in Prysm

### PR DESCRIPTION
**Pull request by mkykadir**
Prysm brought some breaking changes with v3 update, upgrade Prysm module
to support v3.

Fixes #1165 actually

### CODE REVIEW

**Review by hewison-chris — APPROVED** [review]
LGTM

**Comment by hewison-chris** [comment]
@guybrush Please consider merging this as it adds support back for Prysm clients.

**Comment by guybrush** [comment]
Thank you! This is a good start to fully support prysm again!

We still need to add support for the bellatrix-fork, after merging this PR.

**Comment by mkykadir** [comment]
@guybrush Can this be merged with just Altair support until then? A new issue may be opened for the Bellatrix support.

**Comment by mkykadir** [comment]
Prysm has Bellatrix block [support](https://github.com/prysmaticlabs/prysm/blob/4e225fc667d8df6f8254803d5ae3122be08fd003/proto/prysm/v1alpha1/beacon_block.proto#L328) in `v2.1.4` but Go package [version](https://pkg.go.dev/github.com/prysmaticlabs/prysm/v2@v2.0.1) is `v2.0.1` which doesn't have that supported.

**Comment by mkykadir** [comment]
I will rework on this, since Prysm has v3 now! 
https://pkg.go.dev/github.com/prysmaticlabs/prysm/v3@v3.0.0-20220820041614-b787fd877ae7

**Comment by mkykadir** [comment]
@guybrush Enabled bellatrix-fork code, bellatrix blocks can be parsed

**Pull request closed without merging**
