### PR TITLE
(BIDS-2548) Add recommended indices

### PR DESCRIPTION
**Pull request by Eisei24**
Add indices that should have a noticeable performance increase without having a large write overhead.

### CODE REVIEW

**Review by Madib036 — APPROVED** [review]

**Review by LuccaBitfly — APPROVED** [review]
utAck. Again, should also let a senior take a look.

**Comment by Eisei24** [comment]
@peterbitfly: Please have a look at the indices that could be added.

**Comment by peterbitfly** [comment]
The index for the blocks_attestations table will get very large as this is the largest table in the db. Which query needs that index?

**Comment by Eisei24** [comment]
@peterbitfly It was recommended for these two identical queries

- https://github.com/gobitfly/eth2-beaconchain-explorer/blob/7ef059aa9855f695babd4a7532ebfae8424f0522/db/db.go#L3204
- https://github.com/gobitfly/eth2-beaconchain-explorer/blob/4824fc66f837717ca820ceae24cc15aae6cb7e66/db/statistics.go#L1025

**Comment by Eisei24** [comment]
This PR will be obsolete so I am closing it.

**Pull request closed without merging**
