### PR TITLE
Add Stakehouse

### PR DESCRIPTION
**Pull request by stakehouse-dev**
Adding Stakehouse to the Beacon Chain Explorer [Staking Services Page](https://beaconcha.in/stakingServices).
Name Of Service- Stakehouse LSD
Website- joinstakehouse.com

### CODE REVIEW

**Comment by Buttaa** [comment]
hi @stakehouse-dev , how does the user have access to the withdrawal key **and** validator key, but only stake 0.0001 without a third party token involved?
Can a user with 0.0001 exit a validator? if not, why not?

**Comment by stakehouse-dev** [comment]
hi @Buttaa  , 

How does the user have access to the withdrawal key and validator key, but only stake 0.0001 without a third party token involved?
Liquid staking derivative network (LSD) is built on top of Stakehouse protocol and LSD is a pooling mechanism on top of the base guarantees given by Stakehouse protocol. 

Docs on LSD: https://docs.joinstakehouse.com/lsd/overview
Docs on Stakehouse: https://docs.joinstakehouse.com/protocol/learn/Stakehouse

All of our security and audit efforts can be seen here: https://joinstakehouse.com/security
More specifically, formal verification dashboard on account management and more: https://joinstakehouse.com/verification

At the Stakehouse level and anything built on top of it such as LSD, node running is permissionless. Node runners generate their own signing keys for running their validators. As per the audit reports, withdrawal credentials are delegated via smart contracts to the debt tokens minted through the Stakehouse protocol after the validator is eligible for activation on the beacon chain. The derivatives are not minted before this point. At any time, they can be burned to receive the underlying staked ETH but this part (withdrawals) is currently in audit with Runtime verification. You may refer to formal audit report(s) which goes to detail on lifecycle management of a validator from the below links:

First: https://github.com/runtimeverification/publications/blob/main/reports/smart-contracts/Blockswap_Stakehouse.pdf

Second: https://github.com/runtimeverification/publications/blob/main/reports/smart-contracts/Blockswap_Stakehouse_2nd_Audit.pdf


Can a user with 0.0001 exit a validator? If not, why not?
Yes

Can a user propose blocks?
https://docs.joinstakehouse.com/lsd/workflow

Node operators can earn block proposal rewards based on how much of the validator they funded. If using the base protocol and the user funded 100% of the validator, all of the rewards are theirs.

**Comment by Buttaa** [comment]
@stakehouse-dev 

> Liquid staking derivative network (LSD) is built on top of Stakehouse protocol and LSD is a pooling mechanism on top of the base guarantees given by Stakehouse protocol.

I'm sorry, but your response didn't quite address the question(s) I had. After reviewing the documentation, it seems that your product involves multiple components, including LSD token and Nope operator. Please understand that my intention is not to doubt your product, but to ensure that our data accurately represents the facts. 

If there are multiple products involved, please add separate rows for each (just like the Rocket Pool one). 
Note that we also added a new column "[No Supermajority client](https://execution-diversity.info/)" , which is not visible on mainnet (yet) - https://sepolia.beaconcha.in/stakingServices

> Can a user with 0.0001 ETH exit a validator?
Yes

How?

**Comment by recy21** [comment]
No answer within a month, I'll close the ticket, if the problem persists, please open a new one.

**Comment by stakehouse-dev** [comment]
> @stakehouse-dev
> 
> > Liquid staking derivative network (LSD) is built on top of Stakehouse protocol and LSD is a pooling mechanism on top of the base guarantees given by Stakehouse protocol.
> 
> I'm sorry, but your response didn't quite address the question(s) I had. After reviewing the documentation, it seems that your product involves multiple components, including LSD token and Nope operator. Please understand that my intention is not to doubt your product, but to ensure that our data accurately represents the facts.
> 
> If there are multiple products involved, please add separate rows for each (just like the Rocket Pool one). Note that we also added a new column "[No Supermajority client](https://execution-diversity.info/)" , which is not visible on mainnet (yet) - https://sepolia.beaconcha.in/stakingServices
> 
> > Can a user with 0.0001 ETH exit a validator?
> > Yes
> 
> How?

Apologies for the delay. The replies to the questions you asked:
LSD is an application that is built on top of Stakehouse protocol and is essentially an LP management of Stakehouse protocol assets. LSD does not exist without Stakehouse protocol. Additionally, it does not have a token - as mentioned it’s just an LP position. Node operator is not a product either, it's just a user segment of permissionless node running. 
We now have a client diversity dashboard for consensus layer which should give some information on this topic:

https://joinstakehouse.com/client-diversity

A user can rage quit from the protocol and get ETH that has been unstaked from the validator where user token deposit has been mapped to.
https://docs.joinstakehouse.com/knowledge/voluntary-redeemability 

Stakehouse protocol combined with LSDs and the hybrid pool and registry model gives precise information about the flow of ETH from an LP down to the exact BLS public key that it funded. You can read about our node operator portfolio here:
https://youtu.be/wDPLWuzRbko
https://www.youtube.com/watch?v=cE4f99D7gLI

You can also see it live on Goerli and mainnet on our consensus layer ETL: 
https://joinstakehouse.com/client-diversity

When a rage quit takes place, LPs are refunded the principle amount they supplied (minus any penalties consensus layer applies) through the rage quit assistant that will re-distribute unstaked ETH amongst all of the LPs that supplied the induction 32 ETH balance in the first place for a specific BLS public key.

**Comment by stakehouse-dev** [comment]
cc @recy21 @Buttaa

**Comment by Buttaa** [comment]
@stakehouse-dev , I am confused about who owns the validator and withdrawal keys. Is it the user or a smart contract? It seems unusual that a user who stakes only 0.001 ETH would have control over keys that holds 32 ETH. Can you clarify this for me?

I would appreciate it if you could take a look at "Rocket Pool (Pool)" on https://beaconcha.in/stakingServices  which has "Smart Contract" as the key owner and include the `No Supermajority client` column in your PR.

**Comment by recy21** [comment]
No answer within 2 weeks, I'll close the ticket, if the problem persists, please open a new one.

**Pull request closed without merging**
