### PR TITLE
(BIDS-1248) Change Api Docs link

### PR DESCRIPTION
**Pull request by Eisei24**

### CODE REVIEW

**Comment by Ameralameri** [comment]
https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2098.patch

**Comment by Ameralameri** [comment]
https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2098.patch

**Comment by Ameralameri** [comment]
From 9897d71b6a7c4d20c009fe3f8550e4363a3e62ce Mon Sep 17 00:00:00 2001
From: spletka <stefan.pletka@bitfly.at>
Date: Fri, 14 Apr 2023 15:17:26 +0200
Subject: [PATCH] (BIDS-1248) Change Api Docs link

---
 handlers/pageData.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/handlers/pageData.go b/handlers/pageData.go
index a20081c97..4e57ab310 100644
--- a/handlers/pageData.go
+++ b/handlers/pageData.go
@@ -416,7 +416,7 @@ func createMenuItems(active string, isMain bool) []types.MainMenuItem {
 						},
 						{
 							Label: "API Docs",
-							Path:  "https://beaconcha.in/api/v1/docs/index.html",
+							Path:  "/api/v1/docs/index.html",
 							Icon:  "fa-book-reader",
 						},
 						{

**Review by D13ce — APPROVED** [review]
lgtm

**Pull request merged**
