### PR TITLE
Add p2p.org staking service

### PR DESCRIPTION
**Pull request by rgb2hsl**
p2p.org added as a staking service prior to https://beaconcha.in/stakingServices requirements

### CODE REVIEW

**Comment by rgb2hsl** [comment]
@Buttaa hi, may I ask about the reason PR not being reviewed and merged? Are there some conditions not met? Please, let me know

**Comment by Buttaa** [comment]
> @Buttaa hi, may I ask about the reason PR not being reviewed and merged? Are there some conditions not met? Please, let me know

image

P2P is already on the staking service page. Any chance you can open a PR which edits entry?
https://sepolia.beaconcha.in/stakingServices

**Comment by rgb2hsl** [comment]
> > @Buttaa hi, may I ask about the reason PR not being reviewed and merged? Are there some conditions not met? Please, let me know
> 
> image
> 
> P2P is already on the staking service page. Any chance you can open a PR which edits entry? https://sepolia.beaconcha.in/stakingServices

Sure! Thanks for pointing this out.

**Comment by rgb2hsl** [comment]
New PR opened https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1946

**Pull request closed without merging**
