### PR TITLE
Fix GitHub spelling

### PR DESCRIPTION
**Pull request by friederbluemle**
Just a couple of minor capitalization fixes: `Github` -> `GitHub`.

### CODE REVIEW

**Comment by Hugoo** [comment]
Let's resolve conflicts and merge this ! 🚀

**Comment by friederbluemle** [comment]
@Hugoo - Conflicts resolved and rebased 🚀

**Comment by Hugoo** [comment]
@qu0b - this one is ready to be merged :)))

**Comment by manuelsc** [comment]
Thank you, we included your contribution in https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1670

**Pull request closed without merging**
