### PR TITLE
Added SharedStake to list of Staking Services

### PR DESCRIPTION
**Pull request by sharedStake-dev**
Hey! 

We're SharedStake. We just launched on mainnet this week and took the liberty of adding ourselves to the page. Thanks in advance for listing us on your site!

### CODE REVIEW

**Comment by Buttaa** [comment]
You may want to add more information to the website except a button to deposit ETH.

**Comment by sharedStake-dev** [comment]
Hey @Buttaa! 
Thanks for the feedback! 
Couple quick Qs hoping you can help with so we can our issues fixed:


1. We link to notion where we have all the information and links to contracts compiled. Should we make the link more obvious? Or would you recommend replicating information from our notion onto the site? 

Screen Shot 2020-12-12 at 5 02 19 PM
The info link will also take you to the notion. Stats show our current smart contract stats.  
Screen Shot 2020-12-12 at 5 15 09 PM


Screen Shot 2020-12-12 at 5 06 54 PM


2. Our CI/CD deploys the site via our github and there's some secrets there. Additionally most of our devs have full time jobs elsewhere and prefer to remain anonymous and push commits using their local git settings and users.  
So as a means to open source quicker rather than later without impacting our velocity we cut a release, anonymized it and released it.    
We were hoping the verified smart contracts with their limited functionality would suffice as it appears its common to be anonymous in this space and your account also seems anonymous.    
For reference we're hoping to follow the harvest.finance model of release in the future. e,g  https://github.com/harvest-finance/harvest/commits/master
This is our repo: https://github.com/SharedStake/SharedStake-ui

Do you think this a strong friction point? 
And seeing anonymous developer accounts making commits on the repo regularly instead of occasional releases would help trust?

**Comment by sharedStake-main** [comment]
@Buttaa

**Comment by sharedStake-main** [comment]
@Buttaa 
Hi Butta, I am one of the founders of SharedStake.
Since you said you didn't find the website appealing so much, we redesigned the Landing page with some additional information.
But our main information source is notion, do you think this is something we need to consider to host inside our app?
We changed our ci/cd to point out our public repository, as you can see there is contribution traffic now. 
Also, I believe this was a very reasonable feedback on your side.
Thank you very much for your feedbacks.
Let me know if you have any other one!

**Comment by sharedStake-dev** [comment]
@Buttaa  so whats up? this kinda reeks of collusion and insider payments at this point.

**Comment by Buttaa** [comment]
@sharedStake-dev @sharedStake-main 
There is a lot of information missing 
- Who are the people behind SharedStake?
- Imprint/Legal notices?
- Where can I find your userbase?

Don't get me wrong but your github project was created recently, and the website does not even explain the project properly and let alone the activity on the repo.
Is there anyone from the eth2 space that can vouch for your product?

**Pull request closed without merging**
